### ISSUE TITLE
Trying to initialize the AudioNodeWorklet but getting this error, any ideas why?

### ISSUE THREAD

**Issue by 432player** [olvb/phaze#5]
This error is pointing to the constructors

Uncaught TypeError: Failed to construct 'AudioWorkletProcessor': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at PhaseVocoderProcessor.OLAProcessor (ola-processor.js?49c6:7)
    at new PhaseVocoderProcessor (phase-vocoder-worklet.js?dfb2:24)

**Comment by olvb** [comment]
It seems you are trying to directly instantiate a `PhaseVocoderProcessor`, instead of registering the worklet and then instantiating an `AudioWorkletNode`, as in:
```js
await audioContext.audioWorklet.addModule('phase-vocoder.js');
let phaseVocoderNode = new AudioWorkletNode(audioContext, 'phase-vocoder-processor');
```
Take a look at `main.js`for more details.
